version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    pre_build:
      commands:
        - echo pre_build phase
    build:
      commands:
        - echo Build start on 'date'
        - mvn install
    post_build:
      commands:
        - echo Build completed on 'date'
artifacts:
  files:
    - target/example-1.2.jar      